version: '3'

services:
  portainer:
    image: portainer/portainer:arm
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "80:9000"
    networks:
      - web_tier
    deploy:
      placement:
        constraints:
          - node.role == manager

  mqtt_broker_on_arm:
    image: ffaerber/mqtt-broker-on-arm:latest
    restart: always
    ports:
      - "1883:1883"
    networks:
      - web_tier
    environment:
      REDIS_HOST: redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  koa_on_arm:
    image: ffaerber/koa-on-arm:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web_tier
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role != manager

  redis:
    image: hypriot/rpi-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      placement:
        constraints:
          - node.role != manager

networks:
  web_tier:


volumes:
  redis-data:
    driver: local
