version: '2'

volumes:
  redis-data:
    driver: local

services:
  redis:
    image: hypriot/rpi-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  portainer:
    image: portainer/portainer:arm
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - 9000
    ports:
      - 80:9000
