version: '3'

services:

  portainer:
    image: portainer/portainer:arm
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "9000:9000"
    deploy:
      placement:
        constraints:
          - node.role == manager

  mqtt_broker_on_arm:
    image: ffaerber/mqtt-broker-on-arm:latest
    ports:
      - "1883:1883"
    environment:
      REDIS_HOST: redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  koa_on_arm:
    image: ffaerber/koa-on-arm:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role != manager

  redis:
    image: hypriot/rpi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      placement:
        constraints:
          - node.name == pi4


volumes:
  redis-data:
    driver: local
