version: '3'

networks:
  outside:
    driver: overlay
    external: true
  inside:
    driver: overlay
    external: false

volumes:
  redis-data:
    driver: local

services:
  portainer:
    image: portainer/portainer:arm
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 80:9000
    networks:
      - outside
    deploy:
      placement:
        constraints:
          - node.role == manager

  guid:
    image: alexellis2/guid-generator-arm:0.1
    restart: always
    ports:
      - 9000:9000
    networks:
      - outside
    deploy:
      replicas: 5
      placement:
        constraints:
          - node.role != manager

  redis:
    image: hypriot/rpi-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - inside
    volumes:
      - redis-data:/data
    deploy:
      placement:
        constraints:
          - node.role != manager
