version: '3.1'

volumes:
  redis_data:
    driver: local
  ethereum_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  backend:

secrets:
  certificate.crt:
    external: true # docker secret create certificate.crt certificate.crt
  private.key:
    external: true # docker secret create private.key private.key



services:

  node_exporter:
    image: zeiot/rpi-node_exporter:0.13.0
    ports:
      - "9100:9100"
    networks:
      backend:
    deploy:
      mode: global

  traefik:
    image: hypriot/rpi-traefik
    command:
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --docker.domain=ffaerber.com
      - --defaultEntryPoints=http,https
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS:/run/secrets/certificate.crt,/run/secrets/private.key
      - --web
      - --web.metrics.prometheus
      - --debug
    networks:
      backend:
        aliases:
          - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /dev/null:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - private_key
      - certificate_crt
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == odroid

  visualizer:
    image: yangxuan8282/armhf-visualizer
    networks:
      - backend
    depends_on:
      - traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      labels:
        - "traefik.backend=visualizer"
        - "traefik.frontend.rule=Host:visualizer.ffaerber.com"
        - "traefik.port=8080"
      placement:
        constraints:
          - node.role == manager

  portainer:
    image: portainer/portainer:arm
    networks:
      - backend
    depends_on:
      - traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:portainer.ffaerber.com"
        - "traefik.port=9000"
      placement:
        constraints:
          - node.role == manager

  mqtt_receiver:
    image: ffaerber/mqtt-receiver-on-arm:latest
    environment:
      MQTT_BROKER_HOST: mqtt://iot.eclipse.org
      MQTT_TOPIC: topic
    deploy:
      placement:
        constraints:
          - node.hostname == pi2

  socketio:
    image: ffaerber/socketio-arm:latest
    environment:
      DEBUG: socket.io*
    networks:
      - backend
    depends_on:
      - traefik
    deploy:
      labels:
        - "traefik.backend=socketio"
        - "traefik.frontend.rule=Host:socketio.ffaerber.com"
        - "traefik.port=3000"
      placement:
        constraints:
          - node.hostname == pi3

  prometheus:
    image: fstehle/rpi-prometheus
    ports:
      - "9090:9090"
    networks:
      backend:
        aliases:
          - prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.local.path=/prometheus
    deploy:
      placement:
        constraints:
          - node.role == manager

  redis:
    image: hypriot/rpi-redis
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      placement:
        constraints:
          - node.hostname == pi4

  geth:
    image: ffaerber/geth-arm:latest
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ethereum_data:/root/.ethereum
    command: geth --cache=32 --syncmode=light --rpc --rpcaddr "0.0.0.0"
    deploy:
      placement:
        constraints:
          - node.hostname == pi4

  whoami:
    image: hypriot/rpi-whoami
    networks:
      - backend
    depends_on:
      - traefik
    deploy:
      labels:
        - "traefik.backend=whoami"
        - "traefik.frontend.rule=Host:whoami.ffaerber.com"
        - "traefik.port=8000"
      replicas: 5
      update_config:
        parallelism: 5
      placement:
        constraints:
          - node.hostname != odroid

  koa_on_arm:
    image: ffaerber/koa-on-arm:latest
    networks:
      - backend
    depends_on:
      - traefik
    deploy:
      labels:
        - "traefik.backend=koa"
        - "traefik.frontend.rule=Host:koa.ffaerber.com"
        - "traefik.port=3000"
      replicas: 3
      update_config:
        parallelism: 2
      placement:
        constraints:
          - node.hostname != odroid
