version: '3.1'

services:

  traefik:
    image: hypriot/rpi-traefik
    command:
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --docker.domain=ffaerber.com
      - --defaultEntryPoints=http,https
      - --entrypoints=Name:http Address::80
      - --entryPoints=Name:https Address::443 TLS:/run/secrets/certificate_crt,/run/secrets/private_key
      - --entryPoints=Name:ws Address::80
      - --web
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /dev/null:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - private_key
      - certificate_crt
    deploy:
      placement:
        constraints:
          - node.role == manager

  portainer:
    image: portainer/portainer:arm
    networks:
      - traefik
    depends_on:
      - traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:portainer.ffaerber.com"
        - "traefik.port=9000"
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: hypriot/rpi-whoami
    networks:
      - traefik
    depends_on:
      - traefik
    deploy:
      labels:
        - "traefik.backend=whoami"
        - "traefik.frontend.rule=Host:whoami.ffaerber.com"
        - "traefik.port=8000"
      replicas: 20
      placement:
        constraints:
          - node.role != manager

  koa_on_arm:
    image: ffaerber/koa-on-arm:latest
    networks:
      - traefik
    depends_on:
      - traefik
    deploy:
      labels:
        - "traefik.backend=koa"
        - "traefik.frontend.rule=Host:koa.ffaerber.com"
        - "traefik.port=3000"
      replicas: 10
      placement:
        constraints:
          - node.role != manager

  mosca:
    image: ffaerber/mqtt-broker-on-arm:latest
    networks:
      - traefik
    depends_on:
      - traefik
      - redis
    environment:
      REDIS_HOST: redis
    deploy:
      labels:
        - "traefik.backend=mosca"
        - "traefik.frontend.rule=Host:mosca.ffaerber.com"
        - "traefik.port=1883"
      placement:
        constraints:
          - node.role == manager

  socketio:
    image: ffaerber/socketio-arm:latest
    environment:
      DEBUG: socket.io*
    networks:
      - traefik
    depends_on:
      - traefik
    deploy:
      labels:
        - "traefik.backend=socketio"
        - "traefik.frontend.rule=Host:socketio.ffaerber.com"
        - "traefik.frontend.entrypoints=ws"
        - "traefik.protocol=ws"
        - "traefik.port=3000"
      placement:
        constraints:
          - node.role == manager

  redis:
    image: hypriot/rpi-redis
    networks:
      - traefik
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      placement:
        constraints:
          - node.hostname == odroid

  geth:
    image: ffaerber/geth-arm:latest
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ethereum_data:/root/.ethereum
    command: geth --cache=32 --syncmode=light --rpc --rpcaddr "0.0.0.0"
    deploy:
      placement:
        constraints:
          - node.hostname == pi3

volumes:
  redis_data:
    driver: local
  ethereum_data:
    driver: local

networks:
  traefik:
    external: true

secrets:
  certificate_crt:
    external: true
  private_key:
    external: true
