version: '3'

services:
  portainer:
    image: portainer/portainer:arm
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "80:9000"
    networks:
      - outside
    deploy:
      placement:
        constraints:
          - node.role == manager
  guid:
    image: alexellis2/guid-generator-arm:0.1
    restart: always
    ports:
      - "9000:9000"
    networks:
      - outside
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role != manager
  hello:
    image: alexellis2/arm-alpinehello
    restart: always
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role != manager
  redis:
    image: hypriot/rpi-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      placement:
        constraints:
          - node.role != manager

networks:
  outside:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 20.0.14.0/24

volumes:
  redis-data:
    driver: local
